version: '3.6'

services:
  postgres:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: gofinance
      POSTGRES_USER: gofinance
      POSTGRES_PASSWORD: gofinance
      TZ: Europe/Berlin
      PGTZ: Europe/Berlin
    restart: always

volumes:
  postgres:
